# Copyright (C) 2026 Generative Bionics S.R.L. All rights reserved.
# This software may be modified and distributed under the terms of the
# BSD-3-Clause license.

# Script mode: cmake -DGIT_EXECUTABLE=<git> -DSOURCE_DIR=<repo> -DFALLBACK_VERSION=<x.y.z>
#                    -DOUTPUT=<header> -P GenerateVersionHeader.cmake
# FALLBACK_VERSION is used when SOURCE_DIR is not a git repository (e.g. source archives).

cmake_minimum_required(VERSION 3.18)

set(version "${FALLBACK_VERSION}")
if(GIT_EXECUTABLE AND EXISTS "${SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --tags --dirty --always --match "v[0-9]*"
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE git_version
    RESULT_VARIABLE result
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
  if(result EQUAL 0)
    if(git_version MATCHES "^v([0-9].*)$")
      set(version "${CMAKE_MATCH_1}")
    else()
      # no tag is reachable, git describe returns only the abbreviated commit hash
      set(version "${FALLBACK_VERSION}-g${git_version}")
    endif()
  endif()
endif()

set(content "// Generated by GenerateVersionHeader.cmake. Do not edit.
#ifndef BIPEDAL_LOCOMOTION_ROBOT_LOGGER_VERSION_H
#define BIPEDAL_LOCOMOTION_ROBOT_LOGGER_VERSION_H

namespace BipedalLocomotion::RobotLogger
{
constexpr auto version = \"${version}\";
} // namespace BipedalLocomotion::RobotLogger

#endif // BIPEDAL_LOCOMOTION_ROBOT_LOGGER_VERSION_H
")

# the header is rewritten only if the version changed to avoid useless recompilations
set(old_content "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old_content)
endif()
if(NOT content STREQUAL old_content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
