/**
 * @copyright 2024 Istituto Italiano di Tecnologia (IIT), 2026 Generative Bionics S.R.L.
 * This software may be modified and distributed under the terms of the BSD-3-Clause license.
 */

#include <algorithm>
#include <atomic>
#include <cstdlib>
#include <chrono>
#include <filesystem>
#include <random>
#include <set>
#include <thread>

// BLF
#include <BipedalLocomotion/ParametersHandler/StdImplementation.h>
#include <BipedalLocomotion/TextLogging/Logger.h>
#include <BipedalLocomotion/YarpUtilities/VectorsCollectionServer.h>

// Catch2
#include <catch2/catch_test_macros.hpp>

// YARP
#include <yarp/sig/Vector.h>
#include <yarp/eigen/Eigen.h>
#include <yarp/os/Bottle.h>
#include <yarp/os/BufferedPort.h>
#include <yarp/os/ConnectionWriter.h>
#include <yarp/os/Network.h>
#include <yarp/os/Port.h>
#include <yarp/os/PortWriter.h>
#include <yarp/robotinterface/XMLReader.h>
#include <yarp/dev/IEncoders.h>
#include <yarp/dev/MultipleAnalogSensorsInterfaces.h>
#include <yarp/dev/PolyDriver.h>

// matioCpp
#include <matioCpp/matioCpp.h>

// This function populate the YARP_DATA_DIRS environment variable to
// ensure that YARP devices from YARP (from YARP install prefix) and BLF (from the build directory of BLF)
// can be correctly found and launched by libYARP_robotinterface
// Once this is used in multiple tests, we can move it to a common place to share it among tests
bool blf_setenv(const std::string &_name, const std::string &_value)
{
#ifdef _WIN32
    if (0 != _putenv_s(_name.c_str(), _value.c_str()))
    {
        return false;
    }
#else
    if (0 != ::setenv(_name.c_str(), _value.c_str(), true))
    {
        return false;
    }
#endif
    return true;
}


bool ensureYARPAndBLFYARPDevicesCanBeFound()
{
    // To make sure that YarpRobotLoggerDevice is found from the build directory, we add CMAKE_BINARY_DIR
    // to YARP_DATA_DIRS
#ifdef _WIN32
    std::string envVarListSeparator = ";";
#else
    std::string envVarListSeparator = ":";
#endif

    // Make sure that BLF devices are available. The build directory comes first so that the
    // devices under test are used instead of any installed version.
    std::string new_yarp_data_dirs_value = std::string(CMAKE_BINARY_DIR) + "/share/yarp";

    // Make sure that YARP devices can be found
    new_yarp_data_dirs_value = new_yarp_data_dirs_value + envVarListSeparator + YARP_DATA_INSTALL_DIR_FULL;

    return blf_setenv("YARP_DATA_DIRS", new_yarp_data_dirs_value);
}

TEST_CASE("Launch simple logger")
{
    // This test launched a dummy logger and verify that it effectively saves some data
    // Locate location of .exe file of ipit-hipac-codesys-embobj-bridge, done in getDirectoryOfExecutable()

    // As a preliminary step, we rename any leftover .md and .mat files contained in the current working directory
    // to .md.bak and .mat.bak, to ensure that they are not mistakenly files generated by this tests
    std::filesystem::path currentPath = std::filesystem::current_path();
    for (const auto& entry : std::filesystem::directory_iterator(currentPath)) {
        if (entry.is_regular_file()) {
            std::filesystem::path filePath = entry.path();
            std::string extension = filePath.extension().string();

            if (extension == ".mat" || extension == ".md") {
                std::filesystem::path newFilePath = filePath;
                newFilePath += ".bak";
                std::filesystem::rename(filePath, newFilePath);
            }
        }
    }

    // We will be opening yarp ports in the tests, but we do not want to run the yarpserver, so let's set YARP
    // in local mode (everything will work fine as long as all the ports are opened in the same process)
    yarp::os::Network network;
    yarp::os::NetworkBase::setLocalMode(true);

    // We ensure that YARP_DATA_DIRS contains the values necessary to find YARP and BLF devices
    REQUIRE(ensureYARPAndBLFYARPDevicesCanBeFound());

    // We hardcode the yarprobotinterface configuration file is in the source directory and passed via
    // target_compile_definitions
    std::filesystem::path pathToXmlConfigurationFile = std::filesystem::path(CMAKE_CURRENT_SOURCE_DIR) / std::filesystem::path("launch-yarp-robot-logger.xml");

    BipedalLocomotion::log()->info("Loading yarprobotinterface file from {}", pathToXmlConfigurationFile.string());

    // Boilerplate to add enable_tags or disable_tags as necessary
    yarp::os::Property yarprobotinterfaceConfig;
    yarp::os::Bottle enableTags;
    yarp::os::Bottle& enableTagsList = enableTags.addList();
    yarp::os::Bottle disableTags;
    yarp::os::Bottle& disableTagsList = disableTags.addList();

    if (enableTagsList.size() > 0)
    {
        yarprobotinterfaceConfig.put("enable_tags", enableTags.get(0));
    }

    if (disableTagsList.size() > 0)
    {
        yarprobotinterfaceConfig.put("disable_tags", disableTags.get(0));
    }

    yarp::robotinterface::XMLReader yarprobotinterfaceReader;
    yarp::robotinterface::XMLReaderResult yarprobotinterfaceInstance = yarprobotinterfaceReader.getRobotFromFile(pathToXmlConfigurationFile.string(), yarprobotinterfaceConfig);

    REQUIRE(yarprobotinterfaceInstance.parsingIsSuccessful);

    // Enter the startup phase, that will open all the devices and  call attach if necessary
    REQUIRE(yarprobotinterfaceInstance.robot.enterPhase(yarp::robotinterface::ActionPhaseStartup));

    // At this point, the system is running and the thread that called the
    // enterPhase methods does not need to do anything else

    BipedalLocomotion::log()->info("yarprobotinterface successfully loaded and started.");

    // Sleep 0.2 second to collect some data
    std::this_thread::sleep_for(std::chrono::milliseconds(200));

    // Now that some time passed, let's read some values that will compare against the values that we will read from the logger, and then close the robotinterface
    double sim_joint_1_pos_read = 0.0;
    double accelerometer_z_read = 0.0;

    // Make sure that the requires devices are there
    // These strings are the name attributes of the device tags specified in launch-yarp-robot-logger.xml
    CHECK(yarprobotinterfaceInstance.robot.hasDevice("sim_controlboard"));
    CHECK(yarprobotinterfaceInstance.robot.hasDevice("sim_imu"));

    // Read encoders
    yarp::dev::IEncoders* iencs=nullptr;
    CHECK(yarprobotinterfaceInstance.robot.device("sim_controlboard").driver()->view(iencs));
    REQUIRE(iencs != nullptr);
    Eigen::VectorXd jointPosRead;
    size_t nrOfJoints = 4;
    jointPosRead.resize(nrOfJoints);
    CHECK(iencs->getEncoders(jointPosRead.data()));

    // Read accelerometer
    yarp::dev::IThreeAxisLinearAccelerometers* ilinacc=nullptr;
    CHECK(yarprobotinterfaceInstance.robot.device("sim_imu").driver()->view(ilinacc));
    REQUIRE(ilinacc != nullptr);
    yarp::sig::Vector accelerometerReadYARP;
    Eigen::VectorXd accelerometerRead;
    size_t nrOfDirectionsInAccelerometer = 3;
    accelerometerRead.resize(nrOfDirectionsInAccelerometer);
    // The device only has one sensor
    size_t sensIndex = 0;
    double timestamp;
    CHECK(ilinacc->getThreeAxisLinearAccelerometerMeasure(sensIndex, accelerometerReadYARP, timestamp));
    accelerometerRead = yarp::eigen::toEigen(accelerometerReadYARP);


    BipedalLocomotion::log()->info("Halting yarprobotinterface.");
    REQUIRE(yarprobotinterfaceInstance.robot.enterPhase(yarp::robotinterface::ActionPhaseInterrupt1));
    REQUIRE(yarprobotinterfaceInstance.robot.enterPhase(yarp::robotinterface::ActionPhaseShutdown));

    // This call is commented as otherwise it can result in segfault, see https://github.com/ami-iit/bipedal-locomotion-framework/issues/872
    // BipedalLocomotion::log()->info("yarprobotinterface successfully halted.");

    // Now that the yarprobotinterface has been halted, let's open our .mat files and check if the log is working
    currentPath = std::filesystem::current_path();
    std::string matLogFilename;
    for (const auto& entry : std::filesystem::directory_iterator(currentPath)) {
        if (entry.is_regular_file()) {
            std::filesystem::path filePath = entry.path();
            std::string extension = filePath.extension().string();

            if (extension == ".mat") {
                matLogFilename = filePath.string();
            }
        }
    }

    // This call is commented as otherwise it can result in segfault, see https://github.com/ami-iit/bipedal-locomotion-framework/issues/872
    // BipedalLocomotion::log()->info("Loading saved log from {}", matLogFilename);
    matioCpp::File savedLog(matLogFilename);

    REQUIRE(savedLog.isOpen());

    const matioCpp::Variable version = savedLog.read("version");
    REQUIRE(version.isValid());
    // in MAT 7.3 files the strings are read as UTF-16
    REQUIRE(!version.asVector<char16_t>()().empty());

    matioCpp::Struct robotLoggerDeviceStruct = savedLog.read("robot_logger_device").asStruct();

    matioCpp::MultiDimensionalArray<double> jointPosLoggedData = robotLoggerDeviceStruct["joints_state"].asStruct()["positions"].asStruct()["data"].asMultiDimensionalArray<double>();
    // The values are constant, so we can just check the first one
    // The size of the each vector is the number of joints (nrOfJoints)
    Eigen::VectorXd jointPosLogged;
    jointPosLogged.resize(nrOfJoints);
    for(size_t i=0; i < jointPosLogged.size(); i++)
    {
        jointPosLogged(i) = jointPosLoggedData({i,0,0});
    }

    REQUIRE(jointPosLogged.isApprox(jointPosRead,  1e-14));

    // The values are constant, so we can just check the first one
    matioCpp::MultiDimensionalArray<double> accelerometerLoggedData = robotLoggerDeviceStruct["accelerometers"].asStruct()["sim_imu_sensor"].asStruct()["data"].asMultiDimensionalArray<double>();
    // The size of the vector is the number of readings of accelerometers (3)
    Eigen::VectorXd accelerometerLogged;
    accelerometerLogged.resize(nrOfDirectionsInAccelerometer);
    for(size_t i=0; i < accelerometerLogged.size(); i++)
    {
        accelerometerLogged(i) = accelerometerLoggedData({i,0,0});
    }

    REQUIRE(accelerometerLogged.isApprox(accelerometerRead,  1e-14));

    // The z component should be near to -9.8
    CHECK(std::abs(accelerometerLogged(2) - (-9.8)) <= 1.0);
}

/** Stream the signal and return the maximum time spent to send the data. */
std::chrono::duration<double> streamExogenousSignal(const std::vector<std::string>& elementNames,
                                                    std::chrono::milliseconds duration)
{
    auto params = std::make_shared<BipedalLocomotion::ParametersHandler::StdImplementation>();
    params->setParameter("remote", "/telemetry_test/logger");

    BipedalLocomotion::YarpUtilities::VectorsCollectionServer server;
    REQUIRE(server.initialize(params));
    REQUIRE(server.populateMetadata("signal", elementNames));
    REQUIRE(server.finalizeMetadata());

    const std::vector<double> data(elementNames.size(), 1.0);
    std::chrono::duration<double> maxSendTime{0};
    const auto end = std::chrono::steady_clock::now() + duration;
    while (std::chrono::steady_clock::now() < end)
    {
        const auto start = std::chrono::steady_clock::now();
        server.prepareData();
        server.clearData();
        server.populateData("signal", data);
        // strict, so the send waits for the delivery of the previous data
        server.sendData(true);
        maxSendTime = std::max<std::chrono::duration<double>>(maxSendTime,
                                                              std::chrono::steady_clock::now()
                                                                  - start);
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
    return maxSendTime;
}

/** Vector whose serialization takes longer than the timeout of a query to the port. */
struct SlowVector : yarp::os::PortWriter
{
    yarp::sig::Vector data{2, 1.0};

    bool write(yarp::os::ConnectionWriter& connection) const override
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(1500));
        return data.write(connection);
    }
};

TEST_CASE("Telemetry with periodic save and exogenous signal reconnection")
{
    using namespace std::chrono_literals;

    // this folder is set in yarp-robot-telemetry.xml
    const std::filesystem::path logFolder = std::filesystem::current_path() / "telemetry_test_logs";
    std::filesystem::remove_all(logFolder);

    yarp::os::Network network;
    yarp::os::NetworkBase::setLocalMode(true);
    REQUIRE(ensureYARPAndBLFYARPDevicesCanBeFound());

    const std::filesystem::path pathToXmlConfigurationFile
        = std::filesystem::path(CMAKE_CURRENT_SOURCE_DIR) / "launch-yarp-robot-telemetry.xml";

    yarp::robotinterface::XMLReader yarprobotinterfaceReader;
    yarp::robotinterface::XMLReaderResult yarprobotinterfaceInstance
        = yarprobotinterfaceReader.getRobotFromFile(pathToXmlConfigurationFile.string());
    REQUIRE(yarprobotinterfaceInstance.parsingIsSuccessful);
    REQUIRE(yarprobotinterfaceInstance.robot.enterPhase(yarp::robotinterface::ActionPhaseStartup));

    // An application busy streaming does not answer to the queries of the other ports. The logger
    // must not consider it disconnected.
    yarp::os::Port busyPort;
    REQUIRE(busyPort.open("/telemetry_test/busy_signal"));
    std::atomic<bool> busyStreaming{true};
    std::chrono::duration<double> busyMaxWriteTime{0};
    std::thread busyWriter([&] {
        const SlowVector message;
        while (busyStreaming)
        {
            // a write without readers returns immediately, spinning would starve the port
            if (busyPort.getOutputCount() == 0)
            {
                std::this_thread::sleep_for(10ms);
                continue;
            }
            const auto start = std::chrono::steady_clock::now();
            busyPort.write(message);
            busyMaxWriteTime = std::max<std::chrono::duration<double>>(
                busyMaxWriteTime,
                std::chrono::steady_clock::now() - start);
        }
    });

    // First session of the application streaming the exogenous signal
    const auto firstSessionMaxSendTime = streamExogenousSignal({"a", "b"}, 3s);

    // The application is closed. The logger should detect it.
    std::this_thread::sleep_for(2s);

    // Second session. The signal has a different structure.
    const auto secondSessionMaxSendTime = streamExogenousSignal({"a", "b", "c"}, 3s);

    busyStreaming = false;
    busyWriter.join();
    busyPort.close();

    // The logger never blocks the applications streaming the signals
    BipedalLocomotion::log()->info("Maximum send time: {} (first session), {} (second session), {} "
                                   "(busy application).",
                                   firstSessionMaxSendTime,
                                   secondSessionMaxSendTime,
                                   busyMaxWriteTime);
    CHECK(firstSessionMaxSendTime < 100ms);
    CHECK(secondSessionMaxSendTime < 100ms);
    CHECK(busyMaxWriteTime < 1600ms);

    REQUIRE(yarprobotinterfaceInstance.robot.enterPhase(yarp::robotinterface::ActionPhaseInterrupt1));
    REQUIRE(yarprobotinterfaceInstance.robot.enterPhase(yarp::robotinterface::ActionPhaseShutdown));

    std::vector<std::filesystem::path> matFiles;
    for (const auto& entry : std::filesystem::directory_iterator(logFolder))
    {
        if (entry.is_regular_file() && entry.path().extension() == ".mat")
        {
            matFiles.push_back(entry.path());
        }
    }

    // The data is saved every 2 seconds and when the device is closed
    REQUIRE(matFiles.size() >= 3);

    auto getField = [](const matioCpp::Struct& parent, const std::string& name) {
        return parent.isFieldExisting(name) ? parent[name].asStruct() : matioCpp::Struct();
    };

    std::vector<double> jointTimestamps;
    std::set<int> connectionIds;
    std::set<int> busyConnectionIds;
    std::vector<double> busyTimestamps;
    bool firstStructureLogged = false;
    bool secondStructureLogged = false;
    bool imuLogged = false;
    bool rgbCameraLogged = false;
    bool depthCameraLogged = false;
    for (const auto& file : matFiles)
    {
        matioCpp::File savedLog(file.string());
        REQUIRE(savedLog.isOpen());
        const matioCpp::Struct root = savedLog.read("robot_logger_device").asStruct();

        const matioCpp::Struct positions
            = getField(getField(root, "joints_state"), "positions");
        if (positions.isFieldExisting("timestamps"))
        {
            const auto timestamps = positions["timestamps"].asVector<double>();
            jointTimestamps.insert(jointTimestamps.end(), timestamps.begin(), timestamps.end());
        }

        const matioCpp::Struct connectionId
            = getField(getField(root, "exogenous_signals_connection_id"), "test_signal");
        if (connectionId.isFieldExisting("data"))
        {
            auto data = connectionId["data"].asMultiDimensionalArray<double>();
            for (std::size_t i = 0; i < data.dimensions()[2]; i++)
            {
                connectionIds.insert(static_cast<int>(data({0, 0, i})));
            }
        }

        const matioCpp::Struct busyConnectionId
            = getField(getField(root, "exogenous_signals_connection_id"), "busy_signal");
        if (busyConnectionId.isFieldExisting("data"))
        {
            auto data = busyConnectionId["data"].asMultiDimensionalArray<double>();
            for (std::size_t i = 0; i < data.dimensions()[2]; i++)
            {
                busyConnectionIds.insert(static_cast<int>(data({0, 0, i})));
            }
        }
        const matioCpp::Struct busySignal = getField(root, "busy_signal");
        if (busySignal.isFieldExisting("timestamps"))
        {
            const auto timestamps = busySignal["timestamps"].asVector<double>();
            busyTimestamps.insert(busyTimestamps.end(), timestamps.begin(), timestamps.end());
        }

        const matioCpp::Struct signal = getField(root, "test_signal");
        firstStructureLogged = firstStructureLogged
                               || getField(signal, "signal").isFieldExisting("data");
        secondStructureLogged = secondStructureLogged
                                || getField(signal, "signal_connection_2").isFieldExisting("data");
        imuLogged = imuLogged
                    || getField(getField(root, "accelerometers"), "sim_imu_sensor")
                           .isFieldExisting("data");

        // Each mat file has its own videos. The images of a video are the ones whose index
        // follows the first zero index in the mat file. A file may have no image if it has been
        // saved right after the previous one.
        const std::string prefix = (file.parent_path() / file.stem()).string();
        const matioCpp::Struct camera = getField(root, "camera");
        auto hasImages = [](const matioCpp::Struct& channel) {
            return channel.isFieldExisting("data")
                   && channel["data"].dimensions().size() == 3
                   && channel["data"].dimensions()[2] > 0;
        };
        if (hasImages(getField(getField(camera, "sim_camera"), "rgb")))
        {
            rgbCameraLogged = true;
            CHECK(std::filesystem::exists(prefix + "_sim_camera_rgb.mp4"));
        }
        if (hasImages(getField(getField(camera, "sim_depth_camera"), "depth")))
        {
            depthCameraLogged = true;
            CHECK(std::filesystem::exists(prefix + "_sim_depth_camera_depth.mkv"));
        }

        const matioCpp::Struct frames = getField(getField(camera, "sim_depth_camera"), "rgb");
        if (!hasImages(frames))
        {
            continue;
        }
        auto indices = frames["data"].asMultiDimensionalArray<std::uint32_t>();
        const std::size_t numberOfRecords = indices.dimensions()[2];
        std::size_t first = 0;
        while (first < numberOfRecords && indices({0, 0, first}) != 0)
        {
            first++;
        }
        REQUIRE(first < numberOfRecords);
        const std::filesystem::path framesFolder = prefix + "_sim_depth_camera_rgb";
        for (std::size_t i = first; i < numberOfRecords; i++)
        {
            const auto index = indices({0, 0, i});
            CHECK(index == i - first);
            CHECK(std::filesystem::exists(framesFolder / ("img_" + std::to_string(index) + ".png")));
        }
    }

    // No robot data is lost while the files are written
    REQUIRE(jointTimestamps.size() > 2);
    std::sort(jointTimestamps.begin(), jointTimestamps.end());
    double maxStep = 0;
    for (std::size_t i = 1; i < jointTimestamps.size(); i++)
    {
        maxStep = std::max(maxStep, jointTimestamps[i] - jointTimestamps[i - 1]);
    }
    CHECK(maxStep < 0.1);

    // Both the sessions of the exogenous signal are logged
    CHECK(connectionIds == std::set<int>{1, 2});
    CHECK(firstStructureLogged);
    CHECK(secondStructureLogged);

    // The cameras and the inertial sensors are retrieved from the attached devices
    CHECK(imuLogged);
    CHECK(rgbCameraLogged);
    CHECK(depthCameraLogged);

    // The busy application (8 s of streaming, a sample every 1.5 s) has been logged without
    // disconnections
    REQUIRE(busyTimestamps.size() > 1);
    std::sort(busyTimestamps.begin(), busyTimestamps.end());
    CHECK(busyTimestamps.back() - busyTimestamps.front() > 3.0);
    CHECK(busyConnectionIds == std::set<int>{1});

    // All the temporary video files have been renamed
    for (const auto& entry : std::filesystem::directory_iterator(logFolder))
    {
        CHECK(entry.path().filename().string().rfind("output_", 0) == std::string::npos);
    }
}
