name: gh-pages
on:
  push:
    branches:
      - '*'
      - '!gh-pages'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          channels: conda-forge
          channel-priority: true
          conda-remove-defaults: true

      - name: Dependencies
        shell: bash -l {0}
        run: |
          conda install doxygen=1.9.1 graphviz gitpython

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd docs
          python3 ./generate_docs.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site

  deploy:
    runs-on: ubuntu-24.04
    needs: [build]
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
