name: gh-pages
on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          channels: conda-forge
          channel-priority: true
          conda-remove-defaults: true

      - name: Dependencies
        shell: bash -l {0}
        run: |
          conda install doxygen=1.9.1 graphviz gitpython

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd docs
          python3 ./generate_docs.py

      - name: Publish docs to gh-pages
        # if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site
          publish_branch: gh-pages
