name: gh-pages
on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          channels: conda-forge
          channel-priority: true
          conda-remove-defaults: true

      - name: Dependencies
        shell: bash -l {0}
        run: |
          conda install doxygen=1.9.1 graphviz gitpython

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd docs
          python3 ./build_docs.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/site

  deploy:
    runs-on: ubuntu-24.04
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
